### PR TITLE
Add ClosureContainer

### PR DESCRIPTION
**Pull request by roxblnfk**
I think such a container can be useful in tests.

In my case, i would like to replace [this container](https://github.com/yiisoft/yii-cycle/blob/master/tests/Schema/Conveyor/Stub/FakeContainer.php#L19-L28).

There I need to mock many classes of the same interface and I'm not going to predefine them in advance.

### CODE REVIEW

**Comment by samdark** [comment]
Can it be part of https://github.com/yiisoft/test-support/blob/master/src/Container/SimpleContainer.php?

**Comment by roxblnfk** [comment]
> Can it be part of https://github.com/yiisoft/test-support/blob/master/src/Container/SimpleContainer.php?

Ofcourse
SimpleContainer can be part of ClosureContainer

**Comment by samdark** [comment]
Let't merge these then. I see no reason to have two separate ones.

**Comment by roxblnfk** [comment]
> Let't merge these then. I see no reason to have two separate ones.

Sir yes sir!

**Review by samdark — APPROVED** [review]

**Pull request merged**
